# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-03 08:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('aId', models.AutoField(primary_key=True, serialize=False)),
                ('context', models.CharField(max_length=1000)),
                ('ctime', models.DateTimeField(auto_now_add=True)),
                ('mtime', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('pId', models.AutoField(primary_key=True, serialize=False)),
                ('photo_location', models.CharField(max_length=256)),
                ('ctime', models.DateTimeField(auto_now_add=True)),
                ('mtime', models.DateTimeField(auto_now=True)),
                ('aId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='twitter.Article')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('uId', models.AutoField(primary_key=True, serialize=False)),
                ('userName', models.CharField(max_length=40)),
                ('password', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
                ('nickname', models.CharField(max_length=20)),
                ('gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male')], max_length=1)),
                ('birthday', models.DateField()),
                ('profile', models.CharField(max_length=256)),
                ('withdrawFlag', models.BooleanField(default=False)),
                ('ctime', models.DateTimeField(auto_now_add=True)),
                ('mtime', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='twitter.User'),
        ),
    ]
