# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-07 06:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile',
            field=models.ImageField(max_length=256, upload_to=''),
        ),
    ]
