# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-07 06:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0002_auto_20170407_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile',
            field=models.ImageField(upload_to='/profile'),
        ),
    ]
