# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-07 08:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0008_auto_20170407_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo_location',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
